
-- us-census-2010-rl.us-census-2010-p
-- Generated by metasheet on 2021-10-06T09:25:51
create table if not exists "us-census-2010-p"(
"RECTYPE" varchar(1),
"SERIALNO" int,
"PNUM" int,
"PSUB" int,
"PWEIGHT" int,
"RELATE" varchar(2),
"RELATEA" int,
"OC" int,
"RC" int,
"SEX" varchar(1),
"SEXA" int,
"SSPA" int,
"AGE" int,
"AGEA" int,
"QTRBIR" int,
"HISPAN" varchar(2),
"HISPANA" int,
"NUMRACE" int,
"WHITE" int,
"BLACK" int,
"AIAN" int,
"ASIAN" int,
"NHAW" int,
"OPI" int,
"OTHER" int,
"RACESHORT" varchar(2),
"RACEDET" varchar(2),
"RACECHKBX" varchar(3),
"RACEA" int,
"GQTYP" varchar(1),
"GQTYPA" int
)
;

-- CSV IMPORT
-- COPY "us-census-2010-p" from 'path-to-csv-file' DELIMITER ',' CSV HEADER ENCODING 'LATIN1';

