
-- us-census-2010-rl.us-census-2010-h
-- Generated by metasheet on 2021-10-06T09:25:51
create table if not exists "us-census-2010-h"(
"RECTYPE" varchar(1),
"SERIALNO" int,
"STATE" varchar(2),
"REGION" varchar(1),
"DIVISION" varchar(1),
"PUMA" varchar(5),
"TOTAREA" int,
"LANDAREA" int,
"SUBSAMPL" int,
"HWEIGHT" int,
"PERSONS" int,
"UNITTYPE" varchar(1),
"HSUBFLG" int,
"VACS" varchar(1),
"VACSA" int,
"TENURE" varchar(1),
"TENUREA" int,
"HHT" varchar(1),
"P60" int,
"P65" int,
"P18" int,
"NPF" int,
"NOCH" int,
"NRCH" int,
"PAOC" varchar(1),
"PARC" varchar(1),
"UPART" varchar(1),
"MULTG" varchar(1)
)
;

-- CSV IMPORT
-- COPY "us-census-2010-h" from 'path-to-csv-file' DELIMITER ',' CSV HEADER ENCODING 'LATIN1';

